### ISSUE TITLE
Error during bosses.

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/Mana-Management#14]
![image](https://user-images.githubusercontent.com/56220993/117045989-717c8500-ad10-11eb-9491-8ce6658ef577.png)

**Comment by royb3** [comment]
SecureActionButtons cannot be moved during combat. We will solve this by implementing the innervate buttons in another way.

**Comment by Arco-Dielhof** [comment]
This is something we do not need to try to fix, as it is just not possible. Closing issue.
